export const API_URL = 'https://via-cool.com:5050'
export const LOGIN = 'token'
export const USER_ME = 'users/me/'
export const FORMATS = 'formats/'
export const ORGANIZATIONS = 'organizations'
export const REPORT='reports/'
